#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  . sharedfuncs
else
  echo "Missing file: sharedfuncs"
  exit 1
fi

if [ -d _acs ]; then
    for files in _acs/*; do
        . $files
    done
else
  echo "Missing directory: _acs"
  exit 1
fi

welcome
check_root
check_archlinux
check_hostname
check_connection
check_pacman_blocked
check_multilib
pacman_key
system_update
#language_selector
configure_sudo
select_user
choose_aurhelper # @todo auto_mode
automatic_mode

while true
do
  print_title "ARCHLINUX U INSTALL - https://github.com/riyyi/aic"
  echo " 1) $(mainmenu_item "${checklist[1]}" "Basic Setup")"
  echo ""
  echo " q) Quit"
  echo ""
  MAINMENU+=" q"
  read_input_options "$MAINMENU"
  for OPT in ${OPTIONS[@]}; do
    case "$OPT" in
      1)
        #add_custom_repositories
        install_basic_setup
        install_ssh
        install_nfs
        install_samba
        install_tlp
        enable_readahead
        install_zram # automode
        install_video_cards
        install_xorg
        font_config
        install_cups
        install_additional_firmwares
        install_git_tor
        checklist[1]=1
        ;;
      "q")
        finish
        ;;
      *)
        invalid_option
        ;;
    esac
  done
done