#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "Missing file: sharedfuncs"
  exit 1
fi

# VARIABLES
  CONNECTION="wireless"         #(wired/wireless)
  USER="rick"

# COMMON FUNCTIONS
  configure_sudo() {
    if ! is_package_installed "sudo" ; then
      package_install "sudo"
    fi
    #Configure sudoers {{{
    if [[ ! -f /etc/sudoers.acs ]]; then
      cp -v /etc/sudoers /etc/sudoers.acs
      ## Uncomment to allow members of group wheel to execute any command
      sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
      ## Same thing without a password (not secure)
      #sed -i '/%wheel ALL=(ALL) NOPASSWD: ALL/s/^#//' /etc/sudoers

      echo "" >> /etc/sudoers
      echo 'Defaults visiblepw' >> /etc/sudoers
    fi
  }

  create_new_user() {
    # Create user
    username=`echo $USER | tr '[:upper:]' '[:lower:]'`
    useradd -m -g users -G wheel -s /bin/bash ${username}
    chfn ${username}
    passwd ${username}

    # Configure user
    cp /etc/skel/.bashrc /home/${username}
    package_install "nano"
    chown -R ${username}:users /home/${username}
  }

  install_aurhelper() {
    if ! is_package_installed "yaourt" ; then
      package_install "base-devel yajl namcap"
      pacman -D --asdeps yajl namcap
      aui_download_packages "package-query yaourt"
      pacman -D --asdeps package-query
      if ! is_package_installed "yaourt" ; then
        echo "${RED}Yaourt not installed.${RESET}"
        exit 0
      fi
    fi
    AUR_PKG_MANAGER="yaourt"
  }

check_root
check_archlinux
check_hostname
check_connection $CONNECTION
check_pacman_blocked
check_multilib
system_update
configure_sudo
create_new_user
install_aurhelper

#pacstrap ${MOUNTPOINT} kdebase networkmanager kdeplasma-applets-plasma-nm