#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

# VARIABLES
  CONNECTION="wireless"         #(wired/wireless)
  LOCALE="en_US"
  KEYMAP="dvorak"               #(us)
  TIMEZONE="Europe/Amsterdam"
  HARDWARECLOCK="utc"           #(utc/localtime)
  HOSTNAME="arch-laptop"
  INSTALLPARTITION="sda"        #(sda/sdb/sdc)

# COMMON FUNCTIONS
  arch_chroot() {
    arch-chroot $MOUNTPOINT /bin/bash -c "${1}"
  }

check_connection

# Update mirrorlist
pacman -Sy

# Install the base system
pacstrap ${MOUNTPOINT} base base-devel

case "$CONNECTION" in
  wired)
    arch_chroot "systemctl enable dhcpcd@${WIRED_DEV}.service"
    break
    ;;
  wireless)
    pacstrap ${MOUNTPOINT} iw wireless_tools wpa_actiond wpa_supplicant dialog
    break
    ;;
esac

# Generate an fstab
genfstab -U -p ${MOUNTPOINT} >> ${MOUNTPOINT}/etc/fstab
nano ${MOUNTPOINT}/etc/fstab

# Locale
arch_chroot "sed -i '/'${LOCALE}.UTF-8'/s/^#//' /etc/locale.gen"
arch_chroot "locale-gen"
echo LANG=${LOCALE}.UTF-8 > ${MOUNTPOINT}/etc/locale.conf
export LANG=${LOCALE}.UTF-8

# Console keymap
echo "KEYMAP=${KEYMAP}" > ${MOUNTPOINT}/etc/vconsole.conf

# Time zone
arch_chroot "ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime"

# Hardware clock
arch_chroot "hwclock --systohc --${HARDWARECLOCK}"

# Hostname
echo ${HOSTNAME} > ${MOUNTPOINT}/etc/hostname
arch_chroot "sed -i '/127.0.0.1/s/$/ '${HOSTNAME}'/' /etc/hosts"
arch_chroot "sed -i '/::1/s/$/ '${HOSTNAME}'/' /etc/hosts"

# Create an initial ramdisk environment
arch_chroot "mkinitcpio -p linux"

# Install and configure a bootloader
pacstrap ${MOUNTPOINT} grub os-prober
arch_chroot "grub-install --target=i386-pc --recheck /dev/${INSTALLPARTITION}"
arch_chroot "grub-mkconfig -o /boot/grub/grub.cfg"

# Set the root password
echo "${BLUE}Enter your new root password${RESET}"
arch_chroot "passwd"

echo "${RED}A copy of RiyyiAUI will be placed in /root directory of your new system ${RESET}"
cp -R `pwd` ${MOUNTPOINT}/root

read -p "${BLUE}Reboot system?${RESET} " x
if [ $x != "n" ] || [ $x != "N" ]; then
  reboot
else
  exit
fi