#!/bin/bash

# VARIABLES
  # COLORS
    BOLD=$(tput bold)
    UNDERLINE=$(tput sgr 0 1)
    RESET=$(tput sgr0)
    # regular colors
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    PURPLE=$(tput setaf 5)
    CYAN=$(tput setaf 6)
    WHITE=$(tput setaf 7)
    # bold
    BRED=${Bold}$(tput setaf 1)
    BGREEN=${Bold}$(tput setaf 2)
    BYELLOW=${Bold}$(tput setaf 3)
    BBLUE=${Bold}$(tput setaf 4)
    BPURPLE=${Bold}$(tput setaf 5)
    BCYAN=${Bold}$(tput setaf 6)
    BWHITE=${Bold}$(tput setaf 7)
  
  ARCHI=`uname -m`
  MOUNTPOINT="/mnt"

  # LOG FILE
    LOG="install_error.log"
    [[ -f $LOG ]] && rm -f $LOG
    PKG_FAIL="install_pkg_fail_list.log"
    [[ -f $PKG_FAIL ]] && rm -f $PKG_FAIL
    
# COMMON FUNCTIONS
  progress() {
    while true; do
      kill -0 $PID &> /dev/null;
      if [[ $? == 0 ]]; then
        sleep 0.25
      else
        wait $PID
	    RETCODE=$?
	    echo "$PID's retcode: $RETCODE" >> $LOG
	    if [[ $RETCODE == 0 ]] || [[ $RETCODE == 255 ]]; then
	      echo -e "${GREEN}(success)${RESET}"
	    else
	      echo -e "${RED}(failed)${RESET}"
	      echo -e "$PKG" >> $PKG_FAIL
	    fi
	    break
      fi
    done
  }

  check_root() {
    if [[ "$(id -u)" != "0" ]]; then
      echo "${RED}ERROR! You must execute the script as the 'root' user.${RESET}"
      exit
    fi
  }

  check_archlinux() {
    if [[ ! -e /etc/arch-release ]]; then
      echo "ERROR! You must execute the script on Arch Linux."
    fi
  }

  check_hostname() {
    if [[ `echo ${HOSTNAME} | sed 's/ //g'` == "" ]]; then
      echo "ERROR! Hostname is not configured."
    fi
  }

  check_pacman_blocked() {
    if [[ -f /var/lib/pacman/db.lck ]]; then
      echo "${RED}ERROR! Pacman is blocked. \nIf not running remove /var/lib/pacman/db.lck.${RESET}"
    fi
  }

  check_connection(){
    connection_test() {
      ping -c 1 google.com &> /dev/null && return 1 || return 0
    }
    WIRED_DEV=`ip link | grep enp | awk '{print $2}' | sed 's/://' | sed '1!d'`
    WIRELESS_DEV=`ip link | grep wlp | awk '{print $2}' | sed 's/://' | sed '1!d'`
    if connection_test; then
      echo "${RED}ERROR! Connection not found.${RESET}"

#case "$1" in
#wired)
#systemctl start dhcpcd@${WIRED_DEV}.service
#;;
#wireless)
#ip link set ${WIRELESS_DEV} up
#wifi-menu ${WIRELESS_DEV}
#;;
#esac
#check_connection
    fi
  }

  start_module() {
    modprobe $1
  }

  add_module() { #{{{
    #check if the number of arguments is less then 2
    for MODULE in $1; do
      [[ $# -lt 2 ]] && MODULE_NAME="$MODULE" || MODULE_NAME="$2"
      echo "$MODULE" >> /etc/modules-load.d/$MODULE_NAME.conf
      start_module "$MODULE"
    done
  }

  add_repository() {
    REPO=${1}
    URL=${2}
    [[ -n ${3} ]] && SIGLEVEL="\nSigLevel = ${3}" || SIGLEVEL=""
    CHECK_REPO=`grep -F "${REPO}" /etc/pacman.conf`
    if [[ -z $CHECK_REPO ]]; then
      echo -e "\n[${REPO}]${SIGLEVEL}\nServer = ${URL}" >> /etc/pacman.conf
      system_update
    fi
  }

  # This option will avoid any problem with packages install
  check_multilib(){
    if [[ $ARCHI == x86_64 ]]; then
      local MULTILIB=`grep -n "\[multilib\]" /etc/pacman.conf | cut -f1 -d:`
      if [[ -z $MULTILIB ]]; then
        echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
        echo -e '\nMultilib repository added into pacman.conf file'
      else
        sed -i "${MULTILIB}s/^#//" /etc/pacman.conf
        local MULTILIB=$(( $MULTILIB + 1 ))
        sed -i "${MULTILIB}s/^#//" /etc/pacman.conf
      fi
    fi
  }

  add_key() {
    pacman-key -r $1
    pacman-key --lsign-key $1
  }

  pacman_key(){
    if [[ ! -d /etc/pacman.d/gnupg ]]; then
      package_install "haveged"
      haveged -w 1024
      pacman-key --init
      pacman-key --populate archlinux
      pkill haveged
      package_remove "haveged"
    fi
  }

  add_line() {
    ADD_LINE=${1}
    FILEPATH=${2}
    CHECK_LINE=`grep -F "${ADD_LINE}" ${FILEPATH}`
    [[ -z $CHECK_LINE ]] && echo "${ADD_LINE}" >> ${FILEPATH}
  }

  # Check if a package is already installed
  is_package_installed() {
    for PKG in $1; do
      pacman -Q $PKG &> /dev/null && return 0;
    done
    return 1
  }

  aui_download_packages() {
    for PKG in $1; do
      # Exec command as user instead of root
      su - ${username} -c "
        [[ ! -d aui_packages ]] && mkdir aui_packages
        cd aui_packages
        curl -o $PKG.tar.gz https://aur.archlinux.org/packages/${PKG:0:2}/$PKG/$PKG.tar.gz
        tar zxvf $PKG.tar.gz
        rm $PKG.tar.gz
        cd $PKG
        makepkg -csi --noconfirm
      "
    done
  }

  # Install package from aur
  aur_package_install() {
    for PKG in $1; do
      if ! is_package_installed "${PKG}" ; then
        echo -ne "${PKG} (AUR) "
        ${AUR_PKG_MANAGER} --noconfirm -S ${PKG} >>"$LOG" 2>&1 &
        PID=$!;progress $PID
      else
        echo -e "${YELLOW}Warning: ${PKG} is up to date --skipping${RESET}"
      fi
    done
  }

  # Install package using pacman
  package_install() {
    for PKG in ${1}; do
      if ! is_package_installed "${PKG}" ; then
        echo -ne "${PKG} "
        pacman -S --noconfirm --needed ${PKG} >>"$LOG" 2>&1 &
        PID=$!;progress $PID
      else
        echo -e "${YELLOW}Warning: ${PKG} is up to date --skipping${RESET}"
      fi
    done
  }

  # Remove package
  package_remove() {
    for PKG in ${1}; do
      if is_package_installed "${PKG}" ; then
        echo -ne "${PKG} "
        pacman -Rcsn --noconfirm ${PKG} >>"$LOG" 2>&1 &
        PID=$!;progress $PID
      else
        echo -e "${YELLOW}Error: target not found: ${PKG}${RESET}"
      fi
    done
  }

  system_update() {
    pacman -Syy
  }

  system_ctl() {
    local ACTION=${1}
    local OBJECT=${2}
    echo -ne "systemctl ${ACTION} ${OBJECT} "
    systemctl ${ACTION} ${OBJECT} >> "$LOG" 2>&1
    PID=$!;progress $PID
  }
