#!/bin/bash

pause_function() { #{{{
    print_line
    if [[ $AUTOMATIC_MODE -eq 0 ]]; then
        read -e -sn 1 -p "Press enter to continue..."
    fi
} #}}}

read_input() { #{{{
    if [[ $AUTOMATIC_MODE -eq 1 ]]; then
        OPTION=$1
    else
        read -p "$prompt1" OPTION
    fi
} #}}}

read_input_text() { #{{{
    if [[ $AUTOMATIC_MODE -eq 1 ]]; then
        OPTION=$2
    else
        read -p "$1 [y/N]: " OPTION
        echo ""
    fi
    
    OPTION=`echo "$OPTION" | tr '[:upper:]' '[:lower:]'`
} #}}}

read_input_options() { #{{{
    local line
    local packages
    if [[ $AUTOMATIC_MODE -eq 1 ]]; then
        array=("$1")
    else
        read -p "$prompt2" OPTION
        array=("$OPTION")
    fi
    
    for line in ${array[@]/,/ }; do
        if [[ ${line/-/} != $line ]]; then
            for ((i=${line%-*}; i<=${line#*-}; i++)); do
              packages+=($i);
            done
        else
            packages+=($line)
        fi
    done
    OPTIONS=("${packages[@]}")
} #}}}
