#!/bin/bash

package_install() { #{{{
    #install packages using pacman
    if [[ $AUTOMATIC_MODE -eq 1 || $VERBOSE_MODE -eq 0 ]]; then
        for PKG in ${1}; do
            local _pkg_repo=`pacman -Sp --print-format %r ${PKG} | uniq | sed '1!d'`
            case $_pkg_repo in
                "core")
                    _pkg_repo="${BRed}${_pkg_repo}${Reset}"
                    ;;
                "extra")
                    _pkg_repo="${BYellow}${_pkg_repo}${Reset}"
                    ;;
                "community")
                    _pkg_repo="${BGreen}${_pkg_repo}${Reset}"
                    ;;
                "multilib")
                    _pkg_repo="${BCyan}${_pkg_repo}${Reset}"
                    ;;
            esac
            
            if ! is_package_installed "${PKG}" ; then
                ncecho " ${BBlue}[${Reset}${Bold}X${BBlue}]${Reset} Installing (${_pkg_repo}) ${Bold}${PKG}${Reset} "
                pacman -S --noconfirm --needed ${PKG} >>"$LOG" 2>&1 &
                pid=$!;progress $pid
            else
                cecho " ${BBlue}[${Reset}${Bold}X${BBlue}]${Reset} Installing (${_pkg_repo}) ${Bold}${PKG}${Reset} exists "
            fi
        done
    else
        pacman -S --needed ${1}
    fi
} #}}}
