#!/bin/bash

#MIRRORLIST {{{
configure_mirrorlist(){
    local countries_code=("AU" "AT" "BY" "BE" "BR" "BG" "CA" "CL" "CN" "CO" "CZ" "DK" "EE" "FI" "FR" "DE" "GR" "HU" "IN" "IE" "IL" "IT" "JP" "KZ" "KR" "LV" "LU" "MK" "NL" "NC" "NZ" "NO" "PL" "PT" "RO" "RU" "RS" "SG" "SK" "ZA" "ES" "LK" "SE" "CH" "TW" "TR" "UA" "GB" "US" "UZ" "VN")
    local countries_name=("Australia" "Austria" "Belarus" "Belgium" "Brazil" "Bulgaria" "Canada" "Chile" "China" "Colombia" "Czech Republic" "Denmark" "Estonia" "Finland" "France" "Germany" "Greece" "Hungary" "India" "Ireland" "Israel" "Italy" "Japan" "Kazakhstan" "Korea" "Latvia" "Luxembourg" "Macedonia" "Netherlands" "New Caledonia" "New Zealand" "Norway" "Poland" "Portugal" "Romania" "Russian" "Serbia" "Singapore" "Slovakia" "South Africa" "Spain" "Sri Lanka" "Sweden" "Switzerland" "Taiwan" "Turkey" "Ukraine" "United Kingdom" "United States" "Uzbekistan" "Viet Nam")
    
    country_list(){
        #`reflector --list-countries | sed 's/[0-9]//g' | sed 's/^/"/g' | sed 's/,.*//g' | sed 's/ *$//g'  | sed 's/$/"/g' | sed -e :a -e '$!N; s/\n/ /; ta'`
        PS3="$prompt1"
        echo "Select your country:"
        
        select country_name in "${countries_name[@]}"; do
            if contains_element "$country_name" "${countries_name[@]}"; then
                country_code=${countries_code[$(( $REPLY - 1 ))]}
                break
            else
                invalid_option
            fi
        done
    }
    
    print_title "MIRRORLIST - https://wiki.archlinux.org/index.php/Mirrors"
    print_info "This option is a guide to selecting and configuring your mirrors, and a listing of current available mirrors."
    
    OPTION=n
    while [[ $AUTOMATIC_MODE -ne 1 -a $OPTION != y ]]; do
        country_list
        read_input_text "Confirm country: $country_name"
    done

    url="https://www.archlinux.org/mirrorlist/?country=${country_code}&use_mirror_status=on"

    tmpfile=$(mktemp --suffix=-mirrorlist)

    # Get latest mirror list and save to tmpfile
    curl -so ${tmpfile} ${url}
    sed -i 's/^#Server/Server/g' ${tmpfile}

    # Backup and replace current mirrorlist file (if new file is non-zero)
    if [[ -s ${tmpfile} ]]; then
    {   
        echo " Backing up the original mirrorlist..."
        mv -i /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig;
    } && {
        echo " Rotating the new list into place..."
        mv -i ${tmpfile} /etc/pacman.d/mirrorlist;
    }
    else
        echo " Unable to update, could not download list."
    fi
  
    # better repo should go first
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.tmp
    rankmirrors /etc/pacman.d/mirrorlist.tmp > /etc/pacman.d/mirrorlist
    rm /etc/pacman.d/mirrorlist.tmp
    # allow global read access (required for non-root yaourt execution)
    chmod +r /etc/pacman.d/mirrorlist

    if [[ $AUTOMATIC_MODE -ne 1 ]]; then
        $EDITOR /etc/pacman.d/mirrorlist
    fi
}
#}}}
