#!/bin/bash

#CONFIGURE MKINITCPIO {{{
configure_mkinitcpio(){
    print_title "MKINITCPIO - https://wiki.archlinux.org/index.php/Mkinitcpio"
    print_info "mkinitcpio is a Bash script used to create an initial ramdisk environment."
    [[ $LUKS -eq 1 ]] && sed -i '/^HOOK/s/block/block keymap encrypt/' ${MOUNTPOINT}/etc/mkinitcpio.conf
    [[ $LVM -eq 1 ]] && sed -i '/^HOOK/s/filesystems/lvm2 filesystems/' ${MOUNTPOINT}/etc/mkinitcpio.conf
    arch_chroot "mkinitcpio -p linux"
}
#}}}
