#!/bin/bash

#DEFAULT EDITOR {{{
select_editor(){
    editors_list=("emacs" "nano" "vi" "vim" "zile");

    editor_list(){
        #`reflector --list-countries | sed 's/[0-9]//g' | sed 's/^/"/g' | sed 's/,.*//g' | sed 's/ *$//g'  | sed 's/$/"/g' | sed -e :a -e '$!N; s/\n/ /; ta'`
        PS3="$prompt1"
        echo -e "Select editor\n"

        select EDITOR in "${editors_list[@]}"; do
            if contains_element "$EDITOR" "${editors_list[@]}"; then
                package_install "$EDITOR"
                break
            else
                invalid_option
            fi
        done
    }

    print_title "DEFAULT EDITOR"
    
    # @AUTOMATIC_MODE
    if [[ $AUTOMATIC_MODE -eq 1 ]]; then
        OPTION=y
        echo "Selected editor: $EDITOR"
        sleep 1
    else
        OPTION=n
    fi
    
    while [[ $OPTION != y ]]; do
        editor_list
        read_input_text "Confirm editor: $EDITOR"
    done
}
#}}}
