#!/bin/bash

#AUR HELPER {{{
choose_aurhelper(){
    print_title "AUR HELPER - https://wiki.archlinux.org/index.php/AUR_Helpers"
    print_info "AUR Helpers are written to make using the Arch User Repository more comfortable."
    print_warning "\tNone of these tools are officially supported by Arch devs."
    aurhelper=("Yaourt" "Packer" "Pacaur")
    PS3="$prompt1"
    echo -e "Choose your default AUR helper to install\n"
    
    select OPT in "${aurhelper[@]}"; do
        case "$REPLY" in
            1)
                print_title "YAOURT - https://wiki.archlinux.org/index.php/Yaourt"
                print_info "Yaourt (Yet AnOther User Repository Tool) is a community-contributed wrapper for pacman which adds seamless access to the AUR, allowing and automating package compilation and installation from your choice of the thousands of PKGBUILDs in the AUR, in addition to the many thousands of available Arch Linux binary packages."
                
                if ! is_package_installed "yaourt" ; then
                    package_install "base-devel yajl namcap"
                    pacman -D --asdeps yajl namcap
                    aui_download_packages "package-query yaourt"
                    pacman -D --asdeps package-query
                    
                    if ! is_package_installed "yaourt" ; then
                        echo "Yaourt not installed. EXIT now"
                        pause_function
                        exit 0
                    fi
                fi

                AUR_PKG_MANAGER="yaourt  --tmp /var/tmp/"
                ;;
            2)
                if ! is_package_installed "packer" ; then
                    package_install "base-devel git jshon"
                    pacman -D --asdeps jshon
                    aui_download_packages "packer"

                    if ! is_package_installed "packer" ; then
                        echo "Packer not installed. EXIT now"
                        pause_function
                        exit 0
                    fi
                fi

                AUR_PKG_MANAGER="packer"
                ;;
            3)
                if ! is_package_installed "pacaur" ; then
                    package_install "base-devel yajl expac"
                    pacman -D --asdeps yajl expac
                    #fix pod2man path
                    ln -s /usr/bin/core_perl/pod2man /usr/bin/
                    aui_download_packages "cower pacaur"
                    pacman -D --asdeps cower
                    
                    if ! is_package_installed "pacaur" ; then
                        echo "Pacaur not installed. EXIT now"
                        pause_function
                        exit 0
                    fi
                fi

                AUR_PKG_MANAGER="pacaur"
                ;;
            *)
                invalid_option
                ;;
        esac

        [[ -n $OPT ]] && break
    done

    pause_function
}
#}}}