#!/bin/bash

#CONFIGURE SUDO {{{
configure_sudo(){
    if ! is_package_installed "sudo" ; then
        print_title "SUDO - https://wiki.archlinux.org/index.php/Sudo"
        package_install "sudo"
    fi
    
    #CONFIGURE SUDOERS {{{
    if [[ ! -f  /etc/sudoers.aui ]]; then
        cp -v /etc/sudoers /etc/sudoers.aui
        ## Uncomment to allow members of group wheel to execute any command
        sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
        ## Same thing without a password (not secure)
        #sed -i '/%wheel ALL=(ALL) NOPASSWD: ALL/s/^#//' /etc/sudoers

        #This config is especially helpful for those using terminal multiplexers like screen, tmux, or ratpoison, and those using sudo from scripts/cronjobs:
        echo "" >> /etc/sudoers
        echo 'Defaults !requiretty, !tty_tickets, !umask' >> /etc/sudoers
        echo 'Defaults visiblepw, path_info, insults, lecture=always' >> /etc/sudoers
        echo 'Defaults loglinelen=0, logfile =/var/log/sudo.log, log_year, log_host, syslog=auth' >> /etc/sudoers
        echo 'Defaults passwd_tries=3, passwd_timeout=1' >> /etc/sudoers
        echo 'Defaults env_reset, always_set_home, set_home, set_logname' >> /etc/sudoers
        echo 'Defaults !env_editor, editor="/usr/bin/vim:/usr/bin/vi:/usr/bin/nano"' >> /etc/sudoers
        echo 'Defaults timestamp_timeout=15' >> /etc/sudoers
        echo 'Defaults passprompt="[sudo] password for %u: "' >> /etc/sudoers
    fi
    #}}}
}
#}}}
