#!/bin/bash

#SAMBA {{{
install_samba(){
    print_title "SAMBA - https://wiki.archlinux.org/index.php/Samba"
    print_info "Samba is a re-implementation of the SMB/CIFS networking protocol, it facilitates file and printer sharing among Linux and Windows systems as an alternative to NFS."
  
    read_input_text "Install Samba" $SAMBA
  
    if [[ $OPTION == y ]]; then
        package_install "samba smbnetfs"
        [[ ! -f /etc/samba/smb.conf ]] && cp /etc/samba/smb.conf.default /etc/samba/smb.conf
        local CONFIG_SAMBA=`cat /etc/samba/smb.conf | grep usershare`
        
        if [[ -z $CONFIG_SAMBA ]]; then
            # configure usershare
            export USERSHARES_DIR="/var/lib/samba/usershare"
            export USERSHARES_GROUP="sambashare"
            mkdir -p ${USERSHARES_DIR}
            groupadd ${USERSHARES_GROUP}
            chown root:${USERSHARES_GROUP} ${USERSHARES_DIR}
            chmod 1770 ${USERSHARES_DIR}
            sed -i -e '/\[global\]/a\\n   usershare path = /var/lib/samba/usershare\n   usershare max shares = 100\n   usershare allow guests = yes\n   usershare owner only = False' /etc/samba/smb.conf
            sed -i -e '/\[global\]/a\\n   socket options = IPTOS_LOWDELAY TCP_NODELAY SO_KEEPALIVE\n   write cache size = 2097152\n   use sendfile = yes\n' /etc/samba/smb.conf
            usermod -a -G ${USERSHARES_GROUP} ${USERNAME}
            sed -i '/user_allow_other/s/^#//' /etc/fuse.conf
            modprobe fuse
        fi
        
        echo "Enter your new samba account password:"
        pdbedit -a -u ${USERNAME}
        
        while [[ $? -ne 0 ]]; do
            pdbedit -a -u ${USERNAME}
        done
        
        # enable services
        system_ctl enable smbd
        system_ctl enable nmbd
        pause_function
    fi
}
#}}}
