#!/bin/bash

#BASIC SETUP {{{
install_basic_setup(){
    print_title "BASH TOOLS - https://wiki.archlinux.org/index.php/Bash"
    package_install "bc rsync mlocate bash-completion pkgstats"

    print_title "NTPd - https://wiki.archlinux.org/index.php/NTPd"
    package_install "ntp"
    is_package_installed "ntp" && ntpd -u ntp:ntp
    pause_function

    print_title "(UN)COMPRESS TOOLS - https://wiki.archlinux.org/index.php/P7zip"
    package_install "zip unzip unrar p7zip"
    pause_function

    print_title "AVAHI - https://wiki.archlinux.org/index.php/Avahi"
    print_info "Avahi is a free Zero Configuration Networking (Zeroconf) implementation, including a system for multicast DNS/DNS-SD discovery. It allows programs to publish and discovers services and hosts running on a local network with no specific configuration."
    package_install "avahi nss-mdns"
    is_package_installed "avahi" && system_ctl enable avahi-daemon
    pause_function

    print_title "ALSA - https://wiki.archlinux.org/index.php/Alsa"
    print_info "The Advanced Linux Sound Architecture (ALSA) is a Linux kernel component intended to replace the original Open Sound System (OSSv3) for providing device drivers for sound cards."
    package_install "alsa-utils alsa-plugins"
    [[ ${ARCHI} == x86_64 ]] && package_install "lib32-alsa-plugins"
    pause_function

    print_title "PULSEAUDIO - https://wiki.archlinux.org/index.php/Pulseaudio"
    print_info "PulseAudio is the default sound server that serves as a proxy to sound applications using existing kernel sound components like ALSA or OSS"
    package_install "pulseaudio pulseaudio-alsa"
    [[ ${ARCHI} == x86_64 ]] && package_install "lib32-libpulse"
    # Automatically switch to newly-connected devices
    add_line "load-module module-switch-on-connect" "/etc/pulse/default.pa"
    pause_function

    print_title "NTFS/FAT/exFAT - https://wiki.archlinux.org/index.php/File_Systems"
    print_info "A file system (or filesystem) is a means to organize data expected to be retained after a program terminates by providing procedures to store, retrieve and update data, as well as manage the available space on the device(s) which contain it. A file system organizes data in an efficient manner and is tuned to the specific characteristics of the device."
    package_install "ntfs-3g dosfstools exfat-utils fuse fuse-exfat autofs"
    is_package_installed "fuse" && add_module "fuse"
    pause_function
}
#}}}
