#!/bin/bash

#USB 3G MODEM {{{
install_usb_modem(){
    print_title "USB 3G MODEM - https://wiki.archlinux.org/index.php/USB_3G_Modem"
    print_info "A number of mobile telephone networks around the world offer mobile internet connections over UMTS (or EDGE or GSM) using a portable USB modem device."

    read_input_text "Install usb 3G modem support" $USBMODEM

    if [[ $OPTION == y ]]; then
        package_install "usbutils usb_modeswitch"
        is_package_installed "networkmanager" && package_install "modemmanager" || package_install "wvdial"
        pause_function
    fi
}
#}}}
