#!/bin/bash

#VIDEO CARDS {{{
install_video_cards(){
    package_install "dmidecode"
    print_title "VIDEO CARD"
    check_vga
    
    #Virtualbox {{{
    if [[ ${VIDEO_DRIVER} == virtualbox ]]; then
        package_install "virtualbox-guest-utils mesa-libgl"
        add_module "vboxguest vboxsf vboxvideo" "virtualbox-guest"
        add_user_to_group ${username} vboxsf
        system_ctl disable ntpd
        system_ctl enable vboxservice
    #}}}
  
    #Bumblebee {{{
    elif [[ ${VIDEO_DRIVER} == bumblebee ]]; then
        XF86_DRIVERS=$(pacman -Qe | grep xf86-video | awk '{print $1}')
        [[ -n $XF86_DRIVERS ]] && pacman -Rcsn $XF86_DRIVERS
        pacman -S --needed xf86-video-intel bumblebee nvidia
        [[ ${ARCHI} == x86_64 ]] && pacman -S --needed lib32-nvidia-utils
        replace_line '*options nouveau modeset=1' '#options nouveau modeset=1' /etc/modprobe.d/modprobe.conf
        replace_line '*MODULES="nouveau"' '#MODULES="nouveau"' /etc/mkinitcpio.conf
        mkinitcpio -p linux
        gpasswd -a ${username} bumblebee
    #}}}
  
    #NVIDIA {{{
    elif [[ ${VIDEO_DRIVER} == nvidia ]]; then
        XF86_DRIVERS=$(pacman -Qe | grep xf86-video | awk '{print $1}')
        [[ -n $XF86_DRIVERS ]] && pacman -Rcsn $XF86_DRIVERS
        pacman -S --needed nvidia{,-utils}
        [[ ${ARCHI} == x86_64 ]] && pacman -S --needed lib32-nvidia-utils
        replace_line '*options nouveau modeset=1' '#options nouveau modeset=1' /etc/modprobe.d/modprobe.conf
        replace_line '*MODULES="nouveau"' '#MODULES="nouveau"' /etc/mkinitcpio.conf
        mkinitcpio -p linux
        nvidia-xconfig --add-argb-glx-visuals --allow-glx-with-composite --composite -no-logo --render-accel -o /etc/X11/xorg.conf.d/20-nvidia.conf;
    #}}}
  
    #Nouveau [NVIDIA] {{{
    elif [[ ${VIDEO_DRIVER} == nouveau ]]; then
        is_package_installed "nvidia" && pacman -Rdds --noconfirm nvidia{,-utils}
        [[ -f /etc/X11/xorg.conf.d/20-nvidia.conf ]] && rm /etc/X11/xorg.conf.d/20-nvidia.conf
        package_install "xf86-video-${VIDEO_DRIVER} mesa-libgl"
        if [[ ${ARCHI} == x86_64 ]]; then
        is_package_installed "lib32-nvidia-utils" && pacman -Rdds --noconfirm lib32-nvidia-utils
        fi
        replace_line '#*options nouveau modeset=1' 'options nouveau modeset=1' /etc/modprobe.d/modprobe.conf
        replace_line '#*MODULES="nouveau"' 'MODULES="nouveau"' /etc/mkinitcpio.conf
        mkinitcpio -p linux
    #}}}
  
    #ATI {{{
    elif [[ ${VIDEO_DRIVER} == ati ]]; then
        is_package_installed "catalyst-total" && pacman -Rdds --noconfirm catalyst-total
        [[ -f /etc/X11/xorg.conf.d/20-radeon.conf ]] && rm /etc/X11/xorg.conf.d/20-radeon.conf
        [[ -f /etc/modules-load.d/catalyst.conf ]] && rm /etc/modules-load.d/catalyst.conf
        [[ -f /etc/X11/xorg.conf ]] && rm /etc/X11/xorg.conf
        package_install "xf86-video-${VIDEO_DRIVER} mesa-libgl"
        add_module "radeon" "ati"
    #}}}
  
    #Intel {{{
    elif [[ ${VIDEO_DRIVER} == intel ]]; then
        package_install "xf86-video-${VIDEO_DRIVER} libva-intel-driver mesa-libgl"
    #}}}
  
    #Vesa {{{
    else
        package_install "xf86-video-${VIDEO_DRIVER} mesa-libgl"
    fi
    #}}}
    
    if [[ ${ARCHI} == x86_64 ]]; then
        is_package_installed "mesa-libgl" && package_install "lib32-mesa-libgl"
    fi
  
  package_remove "dmidecode"
  pause_function
}
#}}}